### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by tornoz** [jshea2/OSC-for-OBS#12]
Hi, 
since this is an electron app, would it be possible to provide a Linux binary ?
Thanks!

**Comment by jshea2** [comment]
I don't have have anything to test it with, but you are correct! Just added to the latest assets.

**Comment by tornoz** [comment]
Thanks for uploading the build !

sadly, it doesn't launch, here is the error output:

`
$ ./OSC-for-OBS
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'node-keys-simulator'
Require stack:
- /mnt/hdd/apps/osc-for-obs/OSC-for-OBS((v2.7.1)-Linux/resources/app.asar/src/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mnt/hdd/apps/osc-for-obs/OSC-for-OBS((v2.7.1)-Linux/resources/app.asar/src/index.js:14:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
`

**Comment by jshea2** [comment]
Sorry for the late response, but finally got around to adding the source code and doing other updates. Let me know if the new bug fix in "[OSC-for-OBS-.v2.7.2.-Linux.zip](https://github.com/jshea2/OSC-for-OBS/releases/download/v2.7/OSC-for-OBS-.v2.7.2.-Linux.zip)" works, the main problem was the npm package was saved as a dev rather then in the final build. Thanks!
